### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by s560** [czy1999/MultiTQ#3]
Hello, I would like to ask why there is an error that the file cannot be found, as shown in the picture. Thank you for your answer.

**Comment by s560** [comment]
![Uploading FileNotFoundError.png…]()

**Comment by czy1999** [comment]
Cannot see the picture, can you upload it again?

**Comment by s560** [comment]
![FileNotFoundError](https://github.com/czy1999/MultiTQ/assets/57036331/8ec8a4c3-5be5-4019-ac93-bbf45b8ef15a)

**Comment by s560** [comment]
The relative path used first reported an error, and the absolute path later reported an error.

**Comment by czy1999** [comment]
Please create corresponding folders at the appropriate locations (MultiTQ/data/questions/processed_questions) for storing the processed dataset.

**Comment by s560** [comment]
Thank you very much! But when I run the code python. /train_qa_model.py --model multiqa, I get another FileNotFindError error, as shown below.

**Comment by s560** [comment]
![屏幕截图 2024-03-08 222950](https://github.com/czy1999/MultiTQ/assets/57036331/0cfb49d8-1fb0-480c-b46a-a476f9f8d144)

**Comment by s560** [comment]
When I try to create the .ckpt file, running this code still got an error, as shown below. Can you give me some advice? Thank you very much.

**Comment by s560** [comment]
![屏幕截图 2024-03-08 183521](https://github.com/czy1999/MultiTQ/assets/57036331/4c83ca3e-99d2-4d4a-b4bb-9660738a904e)

**Comment by pearlzy** [comment]
![image](https://github.com/czy1999/MultiTQ/assets/93815014/5b842968-817e-421c-96e0-b6ccb5f51743)
我找不到Sentence 和 SequenceTagger

**Comment by czy1999** [comment]
The model has not started training, therefore there is no trained model file. Please check the settings for training epochs and other parameters.
