### ISSUE TITLE
help

### ISSUE THREAD

**Issue by pearlzy** [czy1999/MultiTQ#4]
![image](https://github.com/czy1999/MultiTQ/assets/93815014/8c0f2e0f-f03d-4b05-8a06-3f3499841996)
![image](https://github.com/czy1999/MultiTQ/assets/93815014/bb06af95-6469-48e3-a8e5-1ffeea4191ce)
找不到'entity_positions'、Sequence和SequenceTagger

**Comment by czy1999** [comment]
Please install the flair library using pip.

**Comment by czy1999** [comment]
run ```python ner_task.py``` to get the processed data for training
