### ISSUE TITLE
How to represent the day timestamps that no corresponding **d_i** representation in the TKG embedding for day timestamps di?

### ISSUE THREAD

**Issue by nanxfu** [czy1999/MultiTQ#6]
In the paper related to this repository, the 4.2 Multi-Granularity Time Aggregation section described generate the Multi-Granularity time.
that says
```
we first extract all contained daytimestamps d1, d2, ..., dN and their TKG embeddings td1, td2, ..., tdN
```
![image](https://github.com/czy1999/MultiTQ/assets/36119106/8f6eeae3-b301-4c4b-84cc-e9aec3279a18)
How to transform the daytimestamps into TKG embeddings?
the paper method is to extract them(TKG embeddings) from TKG,But if no corresponding **d_i** representation in the TKG embedding for day timestamps di,what will the paper method do?Will the KGE model generate corresponding **d_i** representation for day timestamps di?

**Comment by czy1999** [comment]
> Will the KGE model generate corresponding d_i representation for day timestamps di?

Yes, see detailed information in appendix A.1.
